#!/usr/bin/env ruby

begin
  gem 'tty-prompt'
rescue Gem::LoadError
  puts "Installing 'tty-prompt' gem..."
  `gem install tty-prompt`
  Gem.clear_paths
end

require 'tty-prompt'

prompt = TTY::Prompt.new

def ask
  puts "Please enter a node name or prefix"
  gets.chomp
end

query = ARGV[0] || ask
nodes = `knife node list | grep #{query}`.split("\n")

unless nodes.empty?
  target = prompt.select("Select a node to SSH into", nodes)
  puts target
  exec("ssh #{target}.dox.box")
end

puts "No matching nodes found for '#{query}'"
exit(0)

